### ISSUE TITLE
AED - support turning off/on 3p dungeons

### ISSUE THREAD

**Issue by RheingoldRiver** [TsubakiBotPad/pad-cogs#1193]
`^aed set toggle3p`

default is **enabled**

Either exclude or include the string `Multiplayer` depending on this setting

Also remember to add this status to ^aed show

**Comment by RheingoldRiver** [comment]
![image](https://user-images.githubusercontent.com/18037011/124863574-ea9c9080-df7c-11eb-92d5-54e2e93f9df5.png)

**Comment by kary5678** [comment]
Hi I'm maybe doing this
