### ISSUE TITLE
For `aed edit/remove` support matching a string to existing patterns, in addition to and ask for confirmation, "Do you want to edit/delete 1. Jurond?" etc

### ISSUE THREAD

**Issue by RheingoldRiver** [TsubakiBotPad/pad-cogs#1194]
![image](https://user-images.githubusercontent.com/18037011/120958628-c2233b80-c71d-11eb-9079-c5b865f1fe2a.png)

**Comment by RheingoldRiver** [comment]
If the pattern is found in any of the user's AEDs:

Do you want to edit/delete 1. Jurond?

If not:

Sorry, `{}` does not match any of your existing Auto Event DMs. Printing all of your Auto Event DMs (you can also see this list with `^aed list`:

{aed list}

**Comment by kary5678** [comment]
Hi I'm maybe doing this
