### ISSUE TITLE
Run flame graph on `^id`, it's kind of slow

### ISSUE THREAD

**Issue by RheingoldRiver** [TsubakiBotPad/pad-cogs#1548]
is the jinja substitution slow? something else?

we could pre-create the entire object in the awakenings emoji file, that might help a bit?

**Comment by chasehult** [comment]
It's the historic lookup json dump
![profile](https://user-images.githubusercontent.com/4073569/156105977-d5051e55-0b01-4cbe-a5be-d51cd423a49e.svg)
.
