### ISSUE TITLE
Make a command `^padglobal eventswap` for psb

### ISSUE THREAD

**Issue by RheingoldRiver** [TsubakiBotPad/pad-cogs#1554]
It moves `^currentevent` to `^lastevent` and `^nextevent` to `^currentevent` and changes `^nextevent` to say N/A in `padglobal`

We've never had `lastevent` before, but we should start having it now, so that in case this command is used incorrectly it's easier to undo.

User story:

* User says `^eventswap`
* Tsubaki says: Are you sure you want to update for the new event? Y/N
* No -> nothing happens
* Yes -> Okay, I've updated `^lastevent` and `^currentevent` accordingly, and cleared `^nextevent`.

**Comment by RheingoldRiver** [comment]
`^nextevent` is literally just the text N/A after an update:

![image](https://user-images.githubusercontent.com/18037011/148738060-10c9f755-b5dd-4191-b902-9f1c55de6e47.png)

**Comment by turtleworks** [comment]
I've offered to do this
