### ISSUE TITLE
Add a listener in sfw-fanart to archive twitter links

### ISSUE THREAD

**Issue by RheingoldRiver** [TsubakiBotPad/pad-cogs#1680]
It should:

1. Find posts with links to tweets
2. Delete the post
3. Upload the image and say "Tweet posted by @user, Link to original: <link>" & upload the image directly into the channel

Motivation: To save tweets that are deleted by the author

Remember there's tweets with multiple images so:
* Test with such tweets
* This can't use embeds

**Comment by chasehult** [comment]
This belongs in misc-cogs.
