### ISSUE TITLE
Make PADle cog

### ISSUE THREAD

**Issue by RheingoldRiver** [TsubakiBotPad/pad-cogs#1707]
This is a wordle clone with PAD words. (Fluff's project)

* `^padle` starts a game of PADle (DM only, if used in a general channel it asks if you want to start a game in DM & gives reactions)
* `^padle guess` guesses a word
* `^padle quit` (alias `^padle exit`) exits
* `^padle score` shows your score from today or says "You haven't played a game yet today!"
* We'll also need an event loop that, once a day at midnight (use PAD's midnight I guess?) does the word rollover & handles deregistration of active games (see below)
* Maybe `^padle subscribe` where you can sign up to be sent a DM by Tsubaki at midnight/rollover to remind you to play PADle (this would be a list of users stored in config most likely)

Data to save:
* A table called `padle_words`: idx, date, word
* A table called `padle_guesses` - fk to `padle_words` on idx, user, guess number, word
	* the word `QQQQQQ` will represent a quit/exited game
	* the word `XXXXXX` will represent a timed out game (you lost because the day rollover happened)
* Probably also a config called `active_games` (this is a small amount of data & not permanent so doesn't need to be an SQL table)
	* on game creation, a user gets registered/added to this list
	* on day rollover/word change, all active games/users are removed from here, and these games are immediately lost with the `XXXXXX` word

Stretch goal: Add some bot-wide stats about # of guesses, % of players to have participated in each word, etc. We can start opening more tickets about these once there's an mvp.

**Comment by ethannp** [comment]
comment for assign
