### ISSUE TITLE
[Reserved for Alianin] Create links to dawnglare boards with ^board

### ISSUE THREAD

**Issue by RheingoldRiver** [TsubakiBotPad/pad-cogs#1769]
* `^board GGGGGG GGGGGG GGGGGG GGGGGG GGGGGG` should link you to https://pad.dawnglare.com/?patt=GGGGGGGGGGGGGGGGGGGGGGGGGGGGGG&showfill=1
  * Fill direction is RIGHT then DOWN
  * Validate that there are either 20 (5x4) or 30 (6x5) or 42 (7x6) letters specified
  * If it's 5x4 or 7x6 then add the appropriate board size to the URL (&height=6&width=7 or &height=4&width=5)
  * Remove all spaces
  * Also include the param `&showfill=1` at the end of the url
* `^board -1 LLLLL DDDDD LLLLL DDDDD LLLLL DDDDD` should link you to https://pad.dawnglare.com/?patt=LDLDLDLDLDLDLDLDLDLDLDLDLDLDLD&showfill=1 - the -1 at the start causes it to first invert the pattern and then fill it
  * The spaces are irrelevant to the inversion, it's just the `-1` causing this
  * I think you should do this with matrices but I'm not sure?
  * Fill direction is DOWN then RIGHT
  * Same thing about board sizes

Allowed letters: `RGBLDHXJMPZ`, if any other letter is included, use `send_cancellation_message` (this comes from the library `tsutils` which is on PyPI) to inform that the user has used an invalid color

This should go in the `padinfo` cog in padinfo.py!

**Comment by Alianin** [comment]
Do I need to account for people potentially entering O for bomb instead of X?

**Comment by RheingoldRiver** [comment]
That would be a cool feature to support, but in the future it's possible `O` means something different and then we'd be breaking compatibility with our correction so I think it's better to not.

Also, since I made this ticket, `Z` is now also a possible orb type (it's an empty square with no orb)
