### ISSUE TITLE
Update brachydios to 1500x in ^buttoninfo

### ISSUE THREAD

**Issue by RheingoldRiver** [TsubakiBotPad/pad-cogs#1872]

**Comment by Alianin** [comment]
Are you referencing this line or something else? https://github.com/TsubakiBotPad/pad-cogs/blob/7d708eaafcf792c47a25a4f80a7d6b79356417d2/padinfo/core/button_info.py#L45

**Comment by RheingoldRiver** [comment]
Yep, that's right!
