### ISSUE TITLE
transforminfo command

### ISSUE THREAD

**Issue by RheingoldRiver** [TsubakiBotPad/pad-cogs#272]
Shows an overview of a card including the awakenings of both base & transformed version, as well as the cooldown it takes to transform

### Description
* Show types of transformed version
* Awakenings: Show both pre-transform and transform (bc we wanna count total SB, SBR, etc)
* Show latents but don't bother showing caption that mentions pre-xform cos we know that

### Stats etc
* Leave as-is for now

### Skills
* **Active skill (2cd) (Base: 30 -> 30)**
* Leave description as-is for now
* Leave leader skill as-is for now

## Additional tabs
* Overview tab of base
* Overview tab of transformed card

(Similar to how `^ls` works)

**Comment by turtleworks** [comment]
Now I see why you've asked me to comment: https://github.com/isaacs/github/issues/100
