### ISSUE TITLE
[padinfo] per-server setting to disable tabs in ^id command

### ISSUE THREAD

**Issue by TsubakiBotPad** [TsubakiBotPad/pad-cogs#6]
Add a per-server setting to disable some tabs in ^id command

Motivation: The list of tabs populates kinda slow.

Implementation details:
* This would require human-readable names for the tabs, and should not be done based on number, in case tabs are added or removed. human-readable names should probably just be the same as the commands to focus them individually, so like `otherinfo`, `pic`, `mats`, etc
* A nonexistent tab name in the ignorelist should fail silently not crash
* Bringing up that tab specifically should override it being in the ignorelist but otherwise respect ignorelist, e.g. if pic and otherinfo are in the ignorelist but you do ^pic tsubaki, you would get pic but not otherinfo for this one command
* Collabscroll should respect the same ignorelist (for now at least)
* Command available to modrole

Should probably discuss whether this is actually worth implementing & whether there's other complications prior to spending time on this

**Comment by RheingoldRiver** [comment]
#197 really removes the need for this
