### ISSUE TITLE
If monster is a transforming card, make it use the current version of the transforminfo embed 

### ISSUE THREAD

**Issue by RheingoldRiver** [TsubakiBotPad/pad-cogs#763]
As created in #754:
![image](https://user-images.githubusercontent.com/18037011/107138046-78ddef00-68d7-11eb-93f9-0c719f7966c6.png)

**Comment by turtleworks** [comment]
Do you want the "Avail. killers (pre-xform)" to come back if it's going back in regular id, or do you suppose it's already understood?

**Comment by RheingoldRiver** [comment]
> Do you want the "Avail. killers (pre-xform)" to come back if it's going back in regular id

good call, yeah, but only for the regular id screen version
