### ISSUE TITLE
Augment tfinfo to include the full text of both active skills & leader skills

### ISSUE THREAD

**Issue by RheingoldRiver** [TsubakiBotPad/pad-cogs#764]
This will be possible after #763 is done, because the normal id display will contain the "abbreviated" display of transforming info about the card

**Comment by turtleworks** [comment]
Support 🔺 2️⃣ 3️⃣ etc. for Jiraiya, Super-1, and friends

**Comment by RheingoldRiver** [comment]
![image](https://user-images.githubusercontent.com/18037011/107464294-999b8400-6b25-11eb-934d-e127a8b52bbe.png)
italics! (i used element inspector)
