### ISSUE TITLE
Everyone gets a series tab!

### ISSUE THREAD

**Issue by RheingoldRiver** [TsubakiBotPad/pad-cogs#813]
1. try to just kill mats (or show only mats, if you're looking at a mat)
2. if you're looking at a mat, filter by type here (unclear if this is relevant for any series)
3. if still too many things, show only same base rarity
4. if still too many things, show only same main attr (note: do this by attr of the tree's base; also, x/r cards == r cards e.g. machigan) 
5. if still too many things, show only same sub attr
6. if still too many things, we'll question our definition of series

**Comment by RheingoldRiver** [comment]
when implementing this, make 20 be cls.MAX_SHOWN_MONS instead of a random magic number

**Comment by RheingoldRiver** [comment]
* note, we are still just showing the base card of each tree here, for example:
![image](https://user-images.githubusercontent.com/18037011/110078285-257f8500-7d4d-11eb-81d6-03f88be88ae4.png)

**Comment by turtleworks** [comment]
- [ ] Skip filtering mats by type
- [ ] Make the current tree bold to indicate where we currently are in the pantheon
- [ ] Indicate how the pantheon has been filtered with some method more compact than writing the criteria out
