### ISSUE TITLE
turtle show lfb how to make rem data jsons

### ISSUE THREAD

**Issue by RheingoldRiver** [TsubakiBotPad/pad-cogs#882]
see: #877

**Comment by turtleworks** [comment]
aye aye

**Comment by turtleworks** [comment]
Done; I'm prepared to construct the jsons after lfb obtains a machine's stone cost and the numbers and drop chances of the monsters in it (it's easy for me to do in my text editor so I offered to do it).

I also passed on the clarification note about what to do about monsters like elementals, who were once in the machine but now no longer appear: one big machine with 0 rate for everything.
