### ISSUE TITLE
Change the default date for padglobal `which` commands to from 2000 to 1969

### ISSUE THREAD

**Issue by RheingoldRiver** [TsubakiBotPad/pad-cogs#949]
User request:
![image](https://user-images.githubusercontent.com/18037011/112614392-36249780-8def-11eb-973a-a547e2fe1de4.png)

**Implementation details**
When the edit date of a padglobal `which` command is unknown, currently we set it to January 1, 2000. This request is to set it to January 1, 1969 instead (though Jan 1, 1970 would also work, as the Unix epoch start time).

You will be editing the `padglobal` cog to do this.

**Comment by salamisami** [comment]
It is to note that I requested it being 1969 to make it deliberately obvious its done on purpose. 
Also it has 69 in it xd

**Comment by RheingoldRiver** [comment]
btw, since we marked this as a good first issue, it might be a while until this gets done - we like to keep some issues open for new contributors that are relatively low priority and fairly easy to implement, and this one definitely meets these criteria.
