### ISSUE TITLE
Make ^dumpmsg support embeds, including ones that are longer than 1 message

### ISSUE THREAD

**Issue by RheingoldRiver** [TsubakiBotPad/pad-cogs#968]
So that we can have embeds in ^which that are longer than 2k char, hooray

See also:
* #966 
* #967 

Since we're gonna split on bold headings into individual sections when we make embeds, dumpmsg should recombine those back into bold headings

**Comment by turtleworks** [comment]
Will writing `dumpwhich` resolve this?

**Comment by RheingoldRiver** [comment]
(answered in discord, but, nah let's leave this open, but I'm marking as low priority for now)

**Comment by RheingoldRiver** [comment]
this seems silly at this point lets not do this
